dist: trusty
language: java
jdk: oraclejdk8

before_install:
  - unset TRAVIS
  - wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH

env:
  - FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4
  
install: true
script: mvn -B verify
      
